const $=id=>document.getElementById(id);
const SETTINGS_KEY="insulin-dose-calculator-settings-v1";
const defaults={mode:"meal-correction",glucoseUnit:"mgdl",rounding:0.5,negativeCorrection:true,defaultTarget:"",defaultIcr:"",defaultIsf:"",lowThreshold:70};
let settings=loadSettings();
function loadSettings(){try{const raw=localStorage.getItem(SETTINGS_KEY);return raw?{...defaults,...JSON.parse(raw)}:{...defaults}}catch(e){return {...defaults}}}
function parseNum(v){const n=Number(String(v).replace(/,/g,"").trim());return Number.isFinite(n)?n:null}
function fmt(n,d=1){if(!Number.isFinite(n))return "—";return n.toFixed(d).replace(/\.0$/,"")}
function roundTo(n,inc){return Math.round((n+Number.EPSILON)/inc)*inc}
function displayToMg(v){return settings.glucoseUnit==="mgdl"?v:v*18}
function isfMgToDisplay(v){return settings.glucoseUnit==="mgdl"?v:v/18}
function isfDisplayToMg(v){return settings.glucoseUnit==="mgdl"?v:v*18}
function saveSettings(){settings.defaultTarget=parseNum($("defaultTarget").value)??"";settings.defaultIcr=parseNum($("defaultIcr").value)??"";settings.defaultIsf=parseNum($("defaultIsf").value)??"";settings.lowThreshold=parseNum($("lowThreshold").value)??(settings.glucoseUnit==="mgdl"?70:3.9);localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));$("savedStatus").textContent="Settings saved locally";applyDefaultsToCase(false);setTimeout(()=>$("savedStatus").textContent="Settings stored locally",1200)}
function resetSettings(){settings={...defaults};localStorage.removeItem(SETTINGS_KEY);applySettingsUI();clearCase()}
function applySettingsUI(){document.querySelectorAll("#modeSeg button").forEach(b=>b.classList.toggle("active",b.dataset.mode===settings.mode));document.querySelectorAll("#glucoseUnitSeg button").forEach(b=>b.classList.toggle("active",b.dataset.unit===settings.glucoseUnit));document.querySelectorAll("#roundingSeg button").forEach(b=>b.classList.toggle("active",Number(b.dataset.round)===settings.rounding));document.querySelectorAll("#negativeCorrectionSeg button").forEach(b=>b.classList.toggle("active",(b.dataset.value==="on")===settings.negativeCorrection));const unit=settings.glucoseUnit==="mgdl"?"mg/dL":"mmol/L";const isfUnit=settings.glucoseUnit==="mgdl"?"mg/dL/U":"mmol/L/U";document.querySelectorAll(".glucoseUnitLabel").forEach(x=>x.textContent=unit);document.querySelectorAll(".isfUnitLabel").forEach(x=>x.textContent=isfUnit);$("defaultTarget").value=settings.defaultTarget!==""?settings.defaultTarget:"";$("defaultIcr").value=settings.defaultIcr!==""?settings.defaultIcr:"";$("defaultIsf").value=settings.defaultIsf!==""?settings.defaultIsf:"";$("lowThreshold").value=settings.lowThreshold??(settings.glucoseUnit==="mgdl"?70:3.9);$("mealSection").classList.toggle("hidden",settings.mode==="correction");$("correctionSection").classList.toggle("hidden",settings.mode==="meal");calculate()}
function convertUnit(newUnit){if(newUnit===settings.glucoseUnit)return;["currentGlucose","targetGlucose","defaultTarget","lowThreshold"].forEach(id=>{const el=$(id),n=parseNum(el.value);if(n!==null)el.value=newUnit==="mmol"?(n/18).toFixed(1):Math.round(n*18)});["isf","defaultIsf"].forEach(id=>{const el=$(id),n=parseNum(el.value);if(n!==null)el.value=newUnit==="mmol"?(n/18).toFixed(1):Math.round(n*18)});settings.glucoseUnit=newUnit;settings.defaultTarget=parseNum($("defaultTarget").value)??"";settings.defaultIsf=parseNum($("defaultIsf").value)??"";settings.lowThreshold=parseNum($("lowThreshold").value)??(newUnit==="mgdl"?70:3.9);applySettingsUI();calculateTdd()}
function applyDefaultsToCase(force=false){if((force||!$("targetGlucose").value)&&settings.defaultTarget!=="")$("targetGlucose").value=settings.defaultTarget;if((force||!$("icr").value)&&settings.defaultIcr!=="")$("icr").value=settings.defaultIcr;if((force||!$("isf").value)&&settings.defaultIsf!=="")$("isf").value=settings.defaultIsf;calculate()}
function clearCase(){["carbs","currentGlucose","targetGlucose","icr","isf","iob","tdd"].forEach(id=>$(id).value="");applyDefaultsToCase(true);calculateTdd()}
function calculateTdd(){const tdd=parseNum($("tdd").value);if(tdd===null||tdd<=0){$("estIcr").textContent="—";$("estIsf").textContent="—";return}$("estIcr").textContent=fmt(500/tdd,1);$("estIsf").textContent=fmt(isfMgToDisplay(1800/tdd),1)}
function calculate(){const mode=settings.mode,mealNeeded=mode!=="correction",correctionNeeded=mode!=="meal";const carbs=parseNum($("carbs").value),icr=parseNum($("icr").value),current=parseNum($("currentGlucose").value),target=parseNum($("targetGlucose").value),isfDisplay=parseNum($("isf").value),iob=Math.max(0,parseNum($("iob").value)??0);const mealValid=!mealNeeded||(carbs!==null&&carbs>=0&&icr!==null&&icr>0);const correctionValid=!correctionNeeded||(current!==null&&target!==null&&isfDisplay!==null&&isfDisplay>0);if(!mealValid||!correctionValid){$("finalDose").textContent="—";$("doseSub").textContent="Enter the required inputs";["mealDoseOut","rawCorrectionOut","iobOut","netCorrectionOut","rawTotalOut"].forEach(id=>$(id).textContent="—");updateWarnings(current);return}const mealDose=mealNeeded?carbs/icr:0;let rawCorrection=0,iobDeducted=0,netCorrection=0;if(correctionNeeded){const currentMg=displayToMg(current),targetMg=displayToMg(target),isfMg=isfDisplayToMg(isfDisplay);rawCorrection=(currentMg-targetMg)/isfMg;if(rawCorrection>0){iobDeducted=Math.min(iob,rawCorrection);netCorrection=rawCorrection-iobDeducted}else{netCorrection=settings.negativeCorrection?rawCorrection:0;iobDeducted=0}}const rawTotal=Math.max(0,mealDose+netCorrection),rounded=Math.max(0,roundTo(rawTotal,settings.rounding));$("finalDose").textContent=fmt(rounded,settings.rounding===1?0:1)+" U";$("doseSub").textContent=`Rounded to nearest ${settings.rounding} U`;$("mealDoseOut").textContent=fmt(mealDose,2)+" U";$("rawCorrectionOut").textContent=correctionNeeded?fmt(rawCorrection,2)+" U":"—";$("iobOut").textContent=correctionNeeded?fmt(iobDeducted,2)+" U":"—";$("netCorrectionOut").textContent=correctionNeeded?fmt(netCorrection,2)+" U":"—";$("rawTotalOut").textContent=fmt(rawTotal,2)+" U";updateWarnings(current)}
function updateWarnings(currentDisplay){const box=$("warningBox");box.className="warningBox hidden";box.textContent="";if(currentDisplay===null||settings.mode==="meal")return;const low=parseNum($("lowThreshold").value),currentMg=displayToMg(currentDisplay),lowMg=displayToMg(low??(settings.glucoseUnit==="mgdl"?70:3.9));if(currentMg<lowMg){box.className="warningBox low";box.textContent="Low-glucose flag: address hypoglycemia according to the patient's established clinical plan before relying on a bolus calculation. The arithmetic is shown for reference."}else if(currentMg>=250){box.className="warningBox high";box.textContent="High-glucose flag: this calculator provides bolus arithmetic only and does not assess ketones, infusion-site failure, illness, dehydration, or other sick-day factors."}}
document.querySelectorAll("#modeSeg button").forEach(b=>b.addEventListener("click",()=>{settings.mode=b.dataset.mode;applySettingsUI()}));document.querySelectorAll("#glucoseUnitSeg button").forEach(b=>b.addEventListener("click",()=>convertUnit(b.dataset.unit)));document.querySelectorAll("#roundingSeg button").forEach(b=>b.addEventListener("click",()=>{settings.rounding=Number(b.dataset.round);applySettingsUI()}));document.querySelectorAll("#negativeCorrectionSeg button").forEach(b=>b.addEventListener("click",()=>{settings.negativeCorrection=b.dataset.value==="on";applySettingsUI()}));["carbs","icr","currentGlucose","targetGlucose","isf","iob"].forEach(id=>$(id).addEventListener("input",calculate));$("tdd").addEventListener("input",calculateTdd);$("lowThreshold").addEventListener("input",calculate);$("useIcrEstimate").addEventListener("click",()=>{const tdd=parseNum($("tdd").value);if(tdd&&tdd>0){$("icr").value=(500/tdd).toFixed(1);calculate()}});$("useIsfEstimate").addEventListener("click",()=>{const tdd=parseNum($("tdd").value);if(tdd&&tdd>0){$("isf").value=isfMgToDisplay(1800/tdd).toFixed(1);calculate()}});$("saveSettings").addEventListener("click",saveSettings);$("resetSettings").addEventListener("click",()=>{if(confirm("Reset all saved calculator settings?"))resetSettings()});$("clearCase").addEventListener("click",clearCase);applySettingsUI();applyDefaultsToCase(false);calculateTdd();
